name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
        working-directory: ./frontend
      - name: Typecheck
        run: npm run typecheck
        working-directory: ./frontend
      - name: Format
        run: npm i prettier && npm prettier --write .
        working-directory: ./frontend
      - name: Lint
        run: npm run lint
        working-directory: ./frontend
